/* TRIGGERS */

DROP TRIGGER IF EXISTS TRG_UPDATE_INFO_TIMESTAMP ON USER_INFO;

DROP TRIGGER IF EXISTS TRG_UPDATE_PRODUCTS_TIMESTAMP ON PRODUCTS;

DROP TRIGGER IF EXISTS TRG_UPDATE_CATEGORIES_TIMESTAMP ON CATEGORIES;

DROP TRIGGER IF EXISTS TRG_UPDATE_USER_TIMESTAMP ON USERS;

/* INDICES */

DROP INDEX IF EXISTS IDX_PRODUCTS_PRODUCTNAME;

DROP INDEX IF EXISTS IDX_CATEGORIES_CATEGORYNAME;

DROP INDEX IF EXISTS IDX_USERS_USEREMAIL;

/* ENTITIES */

DROP TABLE IF EXISTS USER_INFO;

DROP TABLE IF EXISTS PRODUCTS;

DROP TABLE IF EXISTS CATEGORIES;

DROP TABLE IF EXISTS USERS;

/* DOMAINS */

DROP DOMAIN IF EXISTS ENTITY_TIMESTAMP;

DROP DOMAIN IF EXISTS CURRENCY;

DROP DOMAIN IF EXISTS REQUIRED_FK;

DROP DOMAIN IF EXISTS REQUIRED_TEXT;

DROP DOMAIN IF EXISTS EMAIL;
