/* TRIGGERS */

DROP TRIGGER IF EXISTS TRG_SYNC_INVOICE_ORDER_PRICE ON ORDERS;

DROP TRIGGER IF EXISTS TRG_UPDATE_ORDERS_TIMESTAMP ON ORDERS;

DROP TRIGGER IF EXISTS TRG_UPDATE_INVOICES_TIMESTAMP ON INVOICES;

DROP TRIGGER IF EXISTS TRG_UPDATE_COMMENTS_TIMESTAMP ON COMMENTS;

DROP TRIGGER IF EXISTS TRG_UPDATE_INFO_TIMESTAMP ON USER_INFO;

DROP TRIGGER IF EXISTS TRG_UPDATE_PRODUCTS_TIMESTAMP ON PRODUCTS;

DROP TRIGGER IF EXISTS TRG_UPDATE_CATEGORIES_TIMESTAMP ON CATEGORIES;

DROP TRIGGER IF EXISTS TRG_UPDATE_USER_TIMESTAMP ON USERS;

/* INDICES */

DROP INDEX IF EXISTS IDX_PRODUCTS_PRODUCTNAME;

DROP INDEX IF EXISTS IDX_CATEGORIES_CATEGORYNAME;

DROP INDEX IF EXISTS IDX_USERS_USEREMAIL;

/* ENTITIES */

DROP TABLE IF EXISTS ORDERS;

DROP TABLE IF EXISTS INVOICES;

DROP TABLE IF EXISTS COMMENTS;

DROP TABLE IF EXISTS USER_INFO;

DROP TABLE IF EXISTS PRODUCTS;

DROP TABLE IF EXISTS CATEGORIES;

DROP TABLE IF EXISTS USERS;

/* DOMAINS */

DROP DOMAIN IF EXISTS ENTITY_TIMESTAMP;

DROP DOMAIN IF EXISTS CURRENCY;

DROP DOMAIN IF EXISTS REQUIRED_FK;

DROP DOMAIN IF EXISTS REQUIRED_TEXT;

DROP DOMAIN IF EXISTS EMAIL;